# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_productorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
